### ISSUE TITLE
Audio video sync (AVSync2?) on v31.0

### ISSUE THREAD

**Issue by tunerooster** [MythTV/mythtv#204]
* **Platform**: NVIDIA Shield TV 2019 model (the tube)

* **MythTV version**: v31.0fixes

* **Package version**: mythfrontend-20200716-arm-v31.0-79-g89d1991ef2.apk

* **Component**: mythfrontend player

### What steps will reproduce the bug?

On my 2017 Shield TV I have installed: mythfrontend-20190724-arm64-v31-Pre-539...apk

On a new 2019 Shield TV (Tube): mythfrontend-20200716-arm-v31.0-79-g89d1991ef2.apk

The 20190724-arm64-v31-Pre-539 works fine.

The new 20200716-arm-v31.0-79 has problems as follows. When seeking:

The audio does not mute when seeking, as it does on 20190724-arm64-v31-Pre-539.
The audio sync gets messed up when seeking, and causes the video to play double speed and without audio.
I did notice the AVSync2 menu option is missing from the Settings->Playback menus on 20200716-arm-v31.0-79, and I do have it set on the 20190724-arm64-v31-Pre-539 version.

Onn the Shield Tube, the leanback-frontend plays and seeks without error.

### How often does it reproduce? Is there a required condition?

Randomly when seeking forward and/or  backward.  Occasionally, it kills the frontend completely and returns to android.

### What is the expected behaviour?

To have it work like id does in mythfrontend-20190724-arm64-v31-Pre-539...apk
It works flawlessly in that release.  I would install Pre-539 on the 2019 Tube Shield, but the Tube is a 32-bit version of android and requires a 32 bit mythfrontend, which I could not find in a Pre-539 release.

Something that changed from mythfrontend-20190724-arm64-v31-Pre-539...apk to mythfrontend-20200716-arm-v31.0-79-g89d1991ef2.apk seems to be the cause.

So I hope a fix results in the following:

1. mutes audio while seeking (without little audio blips between each seek)
2. resumes playing smoothly and without muted speedup or crashing

### What do you see instead?

Audio gets out of sync with video between pressing forward/backward keys and, often, when playback resumes, the audio is muted and the playback speed is 2X (or so) fast.  I have to exit playback and resume playback to recover.  Sometimes, mythfrontend dies.

### Additional information

jpilk suggested:

Most of the a/v sync issues in the new v31 playback code seem to have been related to the choice of deinterlacer. Perhaps this affects the Shield too.

I have tried all combinations of deinterlacer available in the menus, but to no avail.

**Comment by tunerooster** [comment]
Anyone else have mythtv on the new NVIDIA Shield TV 2019 (the tube) 32bit android release?  Does seek work properly for you?

mythfrontend-20200716-arm-v31.0-79-g89d1991ef2.apk

**Comment by bennettpeter** [comment]
The major difference between v31-pre and v31 is the opengl interop. Have you tried selecting "Android MediaCodec acceleration (decode only)" in the video playback profile? This should disable interop.

**Comment by tunerooster** [comment]
Actually, that *is* the setting I am using, but thanks for the tip...  The
problem continues to persist.  Any other suggestions are gratefully welcome!

Regards...

**Comment by bennettpeter** [comment]
Suggestion: android-MythTV-Leanfront. Are there things that are missing in leanfront that are important to you?

**Comment by tunerooster** [comment]
Yes, Guide data is the first thing I can think of.  I remember there were
several others, but I would have to go back and check.  After so many years
with mythfrontend, I use so many of its features...  I assume frontend will
get fixed eventually.  For a non administrative user,
leanfront would be great, but I am to set in my ways.

Do you know if anyone is working on the sync problem.  Why is it ok in
leanfront but not in frontend?

**Comment by mark-kendall** [comment]
So background first:-

1 UI and video rendering was significantly re-written for 0.31. I'm not sure how old the previous pre .31 version was but the pertinent change here is that what was avsync2 became the only av sync method - i.e. if you were using avsync2 then you are still using it.

2 Comparisons with the leanback frontend are largely useless. Completely different playback code in every regard.

3 Fully accelerated MediaCodec playback (i.e. decoding and rendering) is still a work in progress and requires some significant surgery to the base decoder code to properly fix it. The main issues are lengthy pauses in playback when seeking etc That will hopefully make it into v32

With that in mind, can you provide some further detail:

- what type of material are you playing? (i.e. 4K/HD/SD, MPEG2/H264/HEVC, interlaced v progressive etc)
- does the issue present with any material?
- is there any difference between seeking with pre-recorded MythTV material vs videos?
- what are your playback profile details? (Decoder, video renderer,  deinterlacer quality and preferences)
- what is your audio setup (output device etc)

Can you try the following:

- switch to software decoding (Decoder='Standard') and different combinations of 'OpenGL' and 'OpenGL YV12' for the video renderer and different combinations of deinterlacer settings (different qualities and enable/disable 'Prefer OpenGL deinterlacers')
- switch to '"Android MediaCodec acceleration (decode only)' for decoding and the same combinations as above.
- try adjusting (increasing) the 'Audio read ahead' setting value (Setup->Video->Playback->Advanced Playback Settings)

Note: to adjust your display profiles,  you need to go into the detail for each profile - so don't just switch around the different default profiles. (and apologies if that is obvious!)

**Comment by tunerooster** [comment]
On Thu, Sep 10, 2020 at 3:36 AM Mark Kendall <notifications@github.com>
wrote:

> So background first:-
>
> 1 UI and video rendering was significantly re-written for 0.31. I'm not
> sure how old the previous pre .31 version was but the pertinent change here
> is that what was avsync2 became the only av sync method - i.e. if you were
> using avsync2 then you are still using it.
>
Yes, I was using it in Pre-31 and it was flawless.

I gathered that...  After reviewing lean-frontend again, I see it does not
even try to show video while seeking.  I find that difficult to use.

> 2 Comparisons with the leanback frontend are largely useless. Completely
> different playback code in every regard.
>
I gathered that...  After reviewing lean-frontend again, I see it does not
show video while seeking.  I find that difficult to use.  I can't tell when
a commercial ends.

> 3 Fully accelerated MediaCodec playback (i.e. decoding and rendering) is
> still a work in progress and requires some significant surgery to the base
> decoder code to properly fix it. The main issues are lengthy pauses in
> playback when seeking etc That will hopefully make it into v32
>
With that in mind, can you provide some further detail:
>
>    - what type of material are you playing? (i.e. 4K/HD/SD,
>    MPEG2/H264/HEVC, interlaced v progressive etc)
>
> Over-the-air (recorded with mythbackend) 1080i  MPEG-TS.  From mediainfo:

Video
ID                                       : 49 (0x31)
Menu ID                                  : 1 (0x1)
Format                                   : MPEG Video
Format version                           : Version 2
Format profile                           : Main@High
Format settings                          : CustomMatrix / BVOP
Format settings, BVOP                    : Yes
Format settings, Matrix                  : Custom
Format settings, GOP                     : Variable
Format settings, picture structure       : Frame
Codec ID                                 : 2
Duration                                 : 59 min 47 s
Bit rate mode                            : Variable
Bit rate                                 : 7 592 kb/s
Maximum bit rate                         : 64.0 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Active Format Description                : Full frame 16:9 image
Frame rate                               : 29.970 (30000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Interlaced
Scan order                               : Top Field First
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.122
Stream size                              : 3.17 GiB (88%)
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

>
>    - does the issue present with any material?
>
> The only material I have access to is all the same (other than some
channels broadcast 720p) but I have not seen any difference with those
channels.  They all exhibit the same problem seeking.

>
>    - is there any difference between seeking with pre-recorded MythTV
>    material vs videos?
>
> All I have is MythTV is recorded videos.  If it is important, I can import
some 1080p mkv movies and see if they work.  Do you want me to do that?

>
>    - what are your playback profile details? (Decoder, video renderer,
>    deinterlacer quality and preferences)
>
> Profile: Shield
  Formats: mpeg2video
  Decoder: Android MediaCodec acceleration (decode only) & OpenGL
  Deblocking filter: checked
  Video Renderer: OpenGL (tried YV12, but no difference)
  Deinterlace Quality: High Quality (single rate)
    Prefer driver deinterlacers: checked    (tried unchecked, no difference)
 Deinterlace Quality: High Quality (double rate)
    Prefer driver deinterlacers: checked
>
>
>    - what is your audio setup (output device etc)
>
> Audio Output Device: AudioTrack:
Digital Audio Capabilities: Dolby Digital, DTS, E-AC-3
Speaker Configuration: 7.1
Upmix Quality: Best
HBR Passthrough: checked

>
>
> Can you try the following:
>
>    - switch to software decoding (Decoder='Standard') and different
>    combinations of 'OpenGL' and 'OpenGL YV12' for the video renderer and
>    different combinations of deinterlacer settings (different qualities and
>    enable/disable 'Prefer OpenGL deinterlacers')
>
> Done all that in virtually every combination with no success.  Just
tried  different qualities and enable/disable 'Prefer OpenGL deinterlacers'
again...  no difference.

>
>    - switch to '"Android MediaCodec acceleration (decode only)' for
>    decoding and the same combinations as above.
>
> Done... no difference

>
>    - try adjusting (increasing) the 'Audio read ahead' setting value
>    (Setup->Video->Playback->Advanced Playback Settings)
>
> Audio read ahead is 900 and always has been.  Much lower never worked on
either system...  (no a/v sync issues, just pauses in playback).  Do you
want me to try it even higher?

>
>
> Note: to adjust your display profiles, you need to go into the detail for
> each profile - so don't just switch around the different default profiles.
> (and apologies if that is obvious!)
>
Right, that is what I do.

I should mention, on the Pre-31 2017 Shield (64-bit)  Android version, the
settings are (as specified in the original doc):

Setup -> Video -> Playback Value
Advanced Playback Settings ->
Enable new timestamp based playback speed (AVSync2) checked
Advanced Playback Settings -> Allow YV12 unchecked
Advanced Playback Settings -> Allow UYVY checked
Add a new playback profile shield
shield -> Add New Entry Add two new entries
First entry -> Video Formats mpeg2video
First entry -> Decoder standard
First entry -> Max CPUs 4
First entry -> Video renderer opengl
First entry -> Primary deinterlacer Linear Blend (2x, HW-GL)
First entry -> Fallback deinterlacer Linear Blend (HW-GL)
Second entry -> Video Formats (blank)
Second entry -> Decoder Android MediaCodec decoder
Second entry -> Max CPUs 4
Second entry -> Video renderer opengl
Second entry -> Primary deinterlacer Linear Blend (2x, HW-GL)
Second entry -> Fallback deinterlacer Linear Blend (HW-GL

Thanks so much for your work and help.  Let me know if there is anything
else I can provide!

Best regards,
Dick

**Comment by mark-kendall** [comment]
This sounds like an audio issue. What happens if you switch audio to OpenSLES?

**Comment by tunerooster** [comment]
Done.  Tried OpenSLES: but no difference.  Reverted back to AudioTrack:

**Comment by mark-kendall** [comment]
To be honest - I'm stumped.

The fact that the issue presents regardless of audio and video setup suggest it is a more 'generic' issue yet I haven't seen any similar reports with any builds on other platforms. 

Have you tried a more recent build on the 2017 Shield TV? - trying to understand whether this is something specific to the 32bit build.

**Comment by tunerooster** [comment]
I guess I could try the 32-bit release from the "2019 tube" on the 2017
Shield.  64 bit systems are supposed to run 32 bit images, at least my
Gentoo does.  I don't know if the installer will balk saying it is not abi
compatible.  I'll let you know...

What is it about the muting?  Is there code which specifically mutes for so
many seconds when seeking?  Is that code the same?  Is it set to mute for 2
seconds on a seek, to give it time to resync A/V after a seek?

Also, I was comparing the "Playback Data" OSD screen between the two
systems...  It display A/V Sync milliseconds.

On the 2017, it appears very active (aggressive) ranging from -30 to +30
ms, continuously during regular playback, and even higher after a sync.

On the 2019, is is very small range, usually -2 to +2 ms, and also smaller
when seeking stops.

...in case that is a clue.

Thanks again...

**Comment by tunerooster** [comment]
I just discovered that I no longer have the APK:

mythfrontend-20190724-arm64-v31-Pre-539-gff6bd41e0c0.apk

If I install:

mythfrontend-20200716-arm-v31.0-79-g89d1991ef2.apk

I won't be able to revert back.  Might there be an archive somewhere that
still hosts:

mythfrontend-20190724-arm64-v31-Pre-539-gff6bd41e0c0.apk?

Is it possible/feasible to rebuild
mythfrontend-20190724-arm64-v31-Pre-539-gff6bd41e0c0.apk?
If that is possible, could it be rebuilt as a 32 bit image, i.e.:

mythfrontend-20190724-arm-v31-Pre-539-gff6bd41e0c0.apk

I could then test it on the 2019 shield, and if it worked, you could
compare the changes between the two and narrow down the culprit.

**Comment by mark-kendall** [comment]
Below is an extract from a  '-v playback,audio log'. The audio is paused when seeking. When seeking is complete the audio is reset (not apparent from the logs) and then unpaused.

With that in mind, and re-reading your description of the symptoms  - I suspect the real problem here is not the seeking - but getting av sync correct after the seek. i.e. for some reason av sync is horribly broken after the seek, you get messed up visuals and bits and pieces from the audio as it tries to sort out the problem. Just a guess though:)

`2020-09-15 11:33:40.234504 I [20344/20344] CoreContext tv_play.cpp:6435:DoPlayerSeek  TV::DoPlayerSeek(): 30 seconds
2020-09-15 11:33:40.234560 I [20344/20344] CoreContext audio/audiooutputbase.cpp:905:Pause  AOBase: Pause 1
2020-09-15 11:33:40.234592 I [20344/20344] CoreContext tv_play.cpp:8049:UpdateOSDSeekMessage  UpdateOSDSeekMessage(Skip Ahead, 2)
2020-09-15 11:33:40.241071 I [20344/20398] AudioOutputBase audio/audiooutputbase.cpp:1654:OutputAudioLoop  AOBase: OutputAudioLoop: audio paused
2020-09-15 11:33:40.246753 I [20344/20399] Decoder decoders/avformatdecoder.cpp:566:DoFastForward  AFD: DoFastForward(2183 (397), do discard frames)
2020-09-15 11:33:40.378619 I [20344/20399] Decoder decoders/avformatdecoder.cpp:690:SeekReset  AFD: SeekReset(2182, 0, do flush, do discard)
2020-09-15 11:33:40.378683 I [20344/20399] Decoder videobuffers.cpp:878:DiscardFrames  VideoBuffers::DiscardFrames(1): UPLuUUUAUuUUUU
2020-09-15 11:33:40.378810 I [20344/20399] Decoder videobuffers.cpp:946:DiscardFrames  VideoBuffers::DiscardFrames(1): APAAAAAAAAAAAA -- done
2020-09-15 11:33:40.378841 I [20344/20399] Decoder decoders/avformatdecoder.cpp:726:SeekReset  AFD: SeekReset() flushing
2020-09-15 11:33:40.398769 I [20344/20399] Decoder audio/audiooutputbase.cpp:905:Pause  AOBase: Pause 0
2020-09-15 11:33:40.408425 I [20344/20344] CoreContext mythplayer.cpp:3991:ClearAfterSeek  Player(0): ClearAfterSeek(0)
2020-09-15 11:33:40.408461 I [20344/20344] CoreContext mythplayer.cpp:1951:SetBuffering  Player(0): Waiting for video buffers...
2020-09-15 11:33:40.410989 I [20344/20344] CoreContext audio/audiooutputbase.cpp:905:Pause  AOBase: Pause 0
2020-09-15 11:33:40.413383 I [20344/20344] CoreContext audio/audiooutputbase.cpp:905:Pause  AOBase: Pause 0
2020-09-15 11:33:40.428327 I [20344/20344] CoreContext audio/audiooutputbase.cpp:905:Pause  AOBase: Pause 0
2020-09-15 11:33:40.444830 I [20344/20344] CoreContext audio/audiooutputbase.cpp:905:Pause  AOBase: Pause 0
2020-09-15 11:33:40.460349 I [20344/20344] CoreContext audio/audiooutputbase.cpp:905:Pause  AOBase: Pause 0
2020-09-15 11:33:40.476689 I [20344/20344] CoreContext audio/audiooutputbase.cpp:905:Pause  AOBase: Pause 0
2020-09-15 11:33:40.491845 I [20344/20398] AudioOutputBase audio/audiooutputbase.cpp:1669:OutputAudioLoop  AOBase: OutputAudioLoop: Play Event
`

**Comment by tunerooster** [comment]
How long is the mute after a seek?  On the "issue" system, there is
virtually no audio pause after a seek.  I hear audio immediately, after
each seek, and it is out of sync.  I can then hear the AVSync adjusting the
audio and it resumes play in sync.  But there is a moment of audio
confusion before it gets in sync, and that sometimes seems to cause the
system to mute (and sometimes to crash).  Yet on the 2017 Shield, I can
count to two before the audio is restored, and it is then in sync.  This
results in completely silent seeking (forward, back, in any order), with a
two second wait for audio and the end of the seeking (which is
perfectly acceptable).  Do the logs show anything about the duration of
muting/pausing?  I can't hear it (the pause), it sounds like there is no
pause after a seek.  Then the audio resumes immediately...

Are you testing on:

mythfrontend-20200716-arm-v31.0-79-g89d1991ef2.apk

**Comment by mark-kendall** [comment]
We really need some logs to see what is happening. I'll ping @bennettpeter on how to do that on android - I don't have a running android build atm and he should be able to give some instructions.

**Comment by bennettpeter** [comment]
To get verbose logs - 
- Enable network remote control in the frontend
- restart frontend
- on Linux - telnet <android ip address> 6546
- in telnet - set verbose playback
in linux - adb logcat

**Comment by tunerooster** [comment]
Thanks to Peter, I have verbose logs working.  Is there any specific test
you would like me to run (while capturing logs)?
Should I just seek around a bunch and send the result?

Thanks...

**Comment by tunerooster** [comment]
Peter, thanks, I have it working...  I will send the logs to Mark.  Do you
want a CC?

**Comment by bennettpeter** [comment]
No thanks.

**Comment by mark-kendall** [comment]
Not sure if I'm missing an email or not? @tunerooster did you post some logs somewhere?

**Comment by tunerooster** [comment]
Mark,

Yes I did reply, but I can't find it now.  I must have messed up somehow...

All I said was I was able to get the android log working, and...

Do you want me to just start the log, run a bunch of seeks, forward and
back, until the sound craps out, then send you the log?  Or do you have
something more specific in mind?

Thanks!

**Comment by tunerooster** [comment]
Did you get this?

**Comment by mark-kendall** [comment]
Sorry - juggling too many balls:)

1. start the log (having setup -v playback logging via networkcontrol socket)
2. start playback
3. let it play for a few seconds
4. try seeking
5. If that doesn't induce the issue go back to 3 (i.e wait a few seconds before seeking again)
6. Post log:)

Does that sound OK?

**Comment by tunerooster** [comment]
That sounds fine.  I won't be able to get to it until tomorrow or so.

Regards...

**Comment by tunerooster** [comment]
Ok, here it is...

It took 20 or 30 seconds of seeking to cause it to mute the audio.  I'm not
sure that the "muting" is occurring from mythfrontend or from bad audio
packets sent to my AV receiver (Onkyo), but a restart of mythfrontend is
the only way I have found to recover.  Let me know what you see.  Thanks!

**Comment by mark-kendall** [comment]
I'm not seeing any logs:(

I'm guessing you are sending them as an attachment to an email and github is stripping the attachment (it only recognises certain formats).

I'd suggest either logging on to github and attaching/pasting directly or maybe try sending them as a .txt file - which github seems happy with.

**Comment by tunerooster** [comment]
I resent it.  Did you get it OK this time?

**Comment by mark-kendall** [comment]
Unfortunately not. I think you'll need to log into github.

**Comment by tunerooster** [comment]
Here it is via github...

[avsync.log.gz](https://github.com/MythTV/mythtv/files/5312492/avsync.log.gz)

**Comment by tunerooster** [comment]
Done...

**Comment by mark-kendall** [comment]
Just spotted something in the code that may be relevant. Have you tried completely disabling deinterlacing? Does the problem still occur?

**Comment by tunerooster** [comment]
Done...  No difference.

I set both single rate and double rate quality to "None" without effect.  I
did not restart the frontend...  Do I need to restart?

**Comment by tunerooster** [comment]
Just restarted frontend, just in case.  ...regretfully, it made no
difference.  Let me know if there is anything else I can test...

**Comment by tunerooster** [comment]
You got the logs OK now, right?

**Comment by tunerooster** [comment]
I tried something...

I muted the volume, then seeked around for 5 minutes or more.  Each time,
when I would unmute, following the many seeks, everything is fine.

My theory is, it is not AVSync, but failure to mute while seeking.

Just a theory...  Have you investigated why seeking fails to mute
effectively (long enough)?  Ie, it needs to stay muted for 2 seconds or so,
which then allows avsync to stablize.

**Comment by bennettpeter** [comment]
Mark has left the project so I will try to sort this out. Are you still having the problem? I only have the original shield, not the tube, to test on. Does the 32-bit apk also give the problem on the original shield, or only the tube? Is it consistent or random? If you are still interested in getting this done I can look into the muting theory, and if needed add the mute and unmute code.

**Comment by tunerooster** [comment]
Hi Peter,

Thank you for your interest in this!  The issue has not changed.  I can't
install the 32 bit version on the working machine because l don't have a
copy of the version that works to restore it.

The problem is consistent, in that it continues to happen, maybe 20% of the
seeks through commercials.  Ie, the sound drops out and I have to stop and
restore the program to restore it.

I do still think it is related to muting while seeking as that seems to be
how the original system behaves.

Thanks again for your interest and help!

**Comment by tunerooster** [comment]
I wanted to mention...

My theory is this:
- When seeking through commercials on the tube, mythfrontend fails to mute the sound.
- This causes partial audio packets to be played through the audio system.
- These partial packets intermittently confuse the processing of the audio (either in android, or even in the audio receiver which is passed the raw audio stream over hdmi).
- Every so often the resulting corruption causes either the amp (receiver) or android, to quit, which results in muting, which is only recovered by restarting the program.
- If audio is muted during seek, there are no partial packets processed and the audio can resume after seeking without corruption.

Does this make any sense to you?

Do you know if *muting* during seek is implemented in prior versions of mythfrontend?

Regards,
Dick

**Comment by bennettpeter** [comment]
I do not see this problem. However there do seem to be other problems with playback.
When you say "seeking" are you using skip forward, jump forward or fast forward? Do you use the onscreen menu to select an option, or just right arrow?
Is your audio set up for dolby digital passthrough? Is it set up with opensles or audiotrack?
What I do notice is that with Dolby digital passthrough, audio is out of sync with video and cuts out frequently during normal playback.

**Comment by bennettpeter** [comment]
Update on the above - the playback problems I did notice are solved by increasing the audio read ahead value in mythfrontend setup. The default is 100 ms and this seems to be way too small for most purposes. Set it to 1000 or even more if necessary (mythfrontend->setup->video->playback->advanced->audio read ahead). See if this solves the problem.

**Comment by tunerooster** [comment]
On Sat, May 15, 2021, 12:55 PM Peter Bennett ***@***.***>
wrote:

> I do not see this problem. However there do seem to be other problems with
> playback.
> When you say "seeking" are you using skip forward, jump forward or fast
> forward?
>
Mostly the left and right arrow keys (I assume that is skip
forward/backward).

> Do you use the onscreen menu to select an option, or just right arrow?
>
Just arrows.

> Is your audio set up for dolby digital passthrough?
>
I am sure I use passthrough.  I'm not in front of the system.  Is there an
option for DD?  Isn't that determined by the source?

> Is it set up with opensles or audiotrack?
>
I have tried both.  ...no difference.

> What I do notice is that with Dolby digital passthrough, audio is out of
> sync with video and cuts out frequently during normal playback.
>
I don't see that.  My audio is in sync.

So are you saying you don't think it is a "muting while seek" problem?

**Comment by tunerooster** [comment]
On Sat, May 15, 2021, 1:03 PM Peter Bennett ***@***.***>
wrote:

> Update on the above - the playback problems I did notice are solved by
> increasing the audio read ahead value in mythfrontend setup. The default is
> 100 ms and this seems to be way too small for most purposes. Set it to 1000
> or even more if necessary
> (mythfrontend->setup->video->playback->advanced->audio read ahead). See if
> this solves the problem.
>
I have done this (from the beginning).  It is set at 1000 and has been all
along.  It didn't work well at all without this.

**Comment by bennettpeter** [comment]
I tried this some more. I normally set the forward skip amount to 60 seconds (Setup, video, playback profiles, default). Then to skip a commercial, I press right arrow, then look what is on the screen, press right arrow, look at the screen, etc. Thus there is a second or two between each press. I tried setting it to 15 seconds, and holding down the button so that it repeats very fast. The video jumps some 5 minutes at a time and I do hear some blips of sound, but they could have been generated between key presses, as holding down the button causes hundreds of key presses to be sent. I did not see your issue of losing audio or of video running at double speeed.

Note I am doing my testing on the original shield, using the 32 bit package.

What do you have your forward jumps set to (Setup, video, playback profiles, default)? Do you press the key once at a time, or hold it down so that many presses are sent?

Please use audiotrack for your audio setting.

You mentioned you do not have a certain 32-bit build that you would like to have. I have a whole bunch of old packages for mythtv31 32 bit android. I can add any one that you want to the download site so you can see if that works better, and to help in diagnosing your problem. Let me know which you need:

mythfrontend-20190516-arm-v31-Pre-487-gf3c90896bfc.apk
mythfrontend-20190519-arm-v31-Pre-488-gaf05a71bc3a.apk
mythfrontend-20190620-arm-v31-Pre-510-g7390f5a7e36.apk
mythfrontend-20190724-arm-v31-Pre-539-gff6bd41e0c0.apk
mythfrontend-20200119-arm-v31-Pre-1785-g83d8bbc825.apk
mythfrontend-20200212-arm-v31-Pre-1898-g3f05e59745.apk
mythfrontend-20200227-arm-v31-Pre-1953-ged3bfa425a.apk
mythfrontend-20200323-arm-v31.0.apk
mythfrontend-20200610-arm-v31.0-51-gdd35db8df1.apk
mythfrontend-20200716-arm-v31.0-79-g89d1991ef2.apk

**Comment by tunerooster** [comment]
Great!  This is the version I currently have installed on the 64bit machine:

mythfrontend-20190724-arm64-v31-Pre-539-gff6bd41e0c0.apk

In addition to the above, please post the 32-bit version you would like me
to test...

Will it overwrite all my settings to reinstall it?  Is there any way to
save/restore the settings I have now?  I seem to recall it was quite a bit
of work getting everything setup specific to the Shield.





On Sun, May 16, 2021 at 9:33 AM Peter Bennett ***@***.***>
wrote:

> I tried this some more. I normally set the forward skip amount to 60
> seconds (Setup, video, playback profiles, default). Then to skip a
> commercial, I press right arrow, then look what is on the screen, press
> right arrow, look at the screen, etc. Thus there is a second or two between
> each press. I tried setting it to 15 seconds, and holding down the button
> so that it repeats very fast. The video jumps some 5 minutes at a time and
> I do hear some blips of sound, but they could have been generated between
> key presses, as holding down the button causes hundreds of key presses to
> be sent. I did not see your issue of losing audio or of video running at
> double speeed.
>
> Note I am doing my testing on the original shield, using the 32 bit
> package.
>
> What do you have your forward jumps set to (Setup, video, playback
> profiles, default)? Do you press the key once at a time, or hold it down so
> that many presses are sent?
>
On my version (on the tube
- mythfrontend-20200610-arm-v31.0-51-gdd35db8df1.apk) I do not have the
"Seeking" item you refer to.  Under:
Setup -> Video there is no item names "playback profiles".  Ther is an item
named "Current video playback profile" which is set to "shield", which I
set up.  No "default" profile is displayed.  There is an item named
"Seeking", but it offers only "FF/REW Reposition Amount <100>" which is not
what you are referring to.  I am unable to find any way to set the "skip
amount" and I have looked at all the menu items under "Setup -> Video ".

> Please use audiotrack for your audio setting.
>
Yes, I double checked and I am using  audiotrack

**Comment by bennettpeter** [comment]
> Great! This is the version I currently have installed on the 64bit machine: mythfrontend-20190724-arm64-v31-Pre-539-gff6bd41e0c0.apk In addition to the above, please post the 32-bit version you would like me to test... Will it overwrite all my settings to reinstall it? Is there any way to save/restore the settings I have now? I seem to recall it was quite a bit of work getting everything setup specific to the Shield.

I have added Pre-539, 32 bit version, to the download site https://dl.orangedox.com/pCBmBm in the "Prior Versions" directory.
Just install using `adb install -r apk_filename`. It will not lose or overwrite any of your settings.

> On Sun, May 16, 2021 at 9:33 AM Peter Bennett ***@***.***> wrote: I tried this some more. I normally set the forward skip amount to 60 seconds (Setup, video, playback profiles, default). Then to skip a commercial, I press right arrow, then look what is on the screen, press right arrow, look at the screen, etc. Thus there is a second or two between each press. I tried setting it to 15 seconds, and holding down the button so that it repeats very fast. The video jumps some 5 minutes at a time and I do hear some blips of sound, but they could have been generated between key presses, as holding down the button causes hundreds of key presses to be sent. I did not see your issue of losing audio or of video running at double speeed. Note I am doing my testing on the original shield, using the 32 bit package. What do you have your forward jumps set to (Setup, video, playback profiles, default)? Do you press the key once at a time, or hold it down so that many presses are sent?
> On my version (on the tube - mythfrontend-20200610-arm-v31.0-51-gdd35db8df1.apk) I do not have the "Seeking" item you refer to. Under: Setup -> Video there is no item names "playback profiles". Ther is an item named "Current video playback profile" which is set to "shield", which I set up. No "default" profile is displayed. There is an item named "Seeking", but it offers only "FF/REW Reposition Amount <100>" which is not what you are referring to. I am unable to find any way to set the "skip amount" and I have looked at all the menu items under "Setup -> Video ".

Sorry, the setting is at 
mythfrontend -> Setup -> Video -> Playback Groups -> Default Group
In there are skip ahead and skip back.

**Comment by tunerooster** [comment]
Super!  Got it...  I am looking forward to installing:

     mythfrontend-20190724-arm-v31-Pre-539-gff6bd41e0c0.apk

on the "tube".  I should be able to get to it sometime tomorrow.  I will
also check the settings at:

     Setup -> Video -> Playback Groups -> Default Group

at that time and let you know the results.

Thanks again!!

**Comment by tunerooster** [comment]
I tried to install the 32-bit Pre-539 apk but got the following:

adb: failed to install
/home/rwk/Downloads/mythfrontend-20190724-arm-v31-Pre-539-gff6bd41e0c0.apk:
Failure [-26: Package org.mythtv.mythfrontend new target SDK 21 doesn't
support runtime permissions but the old target SDK 29 does.]

Please advise...

**Comment by tunerooster** [comment]
RE:  Setup -> Video -> Playback Groups -> Default Group

I have skip forward set to 30 and skip back to 5.  I usually press skip
forward 3 or 4 tiles rapidly (but never holding it down), because most of
the commercials are 1.5 to 2 minutes, then briefly see where I am at and
skip again quickly until I see I am over the commercials.  Then, because I
usually overshoot, I click skip back a few times.

Sometimes mythfrontend (on the tube) crashes without saving it's place, and
I have to restart, then skip PAGE FORWARD/BACK until I find where I was,
then regular skip forwards and backwards to narrow in.  As I say, the issue
is very intermittent and only happens 10%-20% of the time, usually after
doing a lot of skipping.

You mentioned you might implement muting during skip.  Is that something
that was taken out of the Pre-539 release?

**Comment by bennettpeter** [comment]
Regarding the failure when installing the package - it looks ike you will have to uninstall and reinstall for that to work. In that case you will lose your settings, but you can get them back if you had set a custom id in "mythfrontend->Setup->General->database Configuration->Use custom identifier for frontend preferences->Custom Identifier". You will have to take note of what that is and set it again after the reinstall. If that was not set (it has my-unique-identifier-goes-here), you have to find out the unique id that android created for you to put back in there. Failing this you will have to do your setups again after reinstall. Even if you do set the correct custom id you will have to download the desired theme again if you had selected a theme.

**Comment by tunerooster** [comment]
Thanks, I will try that and let you know.  Probably sometime tomorrow...

**Comment by bennettpeter** [comment]
I looked at the code for v30 and the latest master. After each seek, forward or backward, it calls MythPlayer::ClearAfterSeek, which, among other things, performs audio reset. This clears all audio buffers and resets the audio time. This was there already in v30. So what happens is: audio from before the seek continues playing until the new position has been located in the recording, at which time the audio is cleared and starts over. No audio discontinuity should happen. Also note that muting the audio before the seek would not change much about this.

Even if you muted audio during the seek, it would still play between button presses, which is what you were worrying about.

If your problem exists with both opensles and audiotrack, it is very unlikely to be audio related, as those two audio methods have completely different implementations.

A new thing added in the latest version is MythPlayer::ClearBeforeSeek, called before every seek, which was not used in V30. This discards video frames, but only when using mediacodec. (Note this code was also NOT in mythfrontend-20190724-arm-v31-Pre-539-gff6bd41e0c0).

Have you tried changing to "standard" decode instead of mediacodec, to see if that fixes the problem? Perhaps this discarding of video frames is doing something wrong.

**Comment by tunerooster** [comment]
Well I got  mythfrontend-20190724-arm-v31-Pre-539-gff6bd41e0c0.apk
installed on the tube, but it is the "leanback frontend" version, which, as
far as I can tell, gives me no way to change back to the original vintage
theme, or access the many features I use all the time.

I *does* however, play recordings flawlessly and is completely silent while
seeking, just like the version I am running on the original
shield: mythfrontend-20190724-arm64-v31-Pre-539-gff6bd41e0c0.apk.  (At
least in the brief testing I did.)

Is there a "non-leanback" Pre-539 arm (32 bit) frontend version on the
download site?

**Comment by bennettpeter** [comment]
mythfrontend-20190724-arm-v31-Pre-539-gff6bd41e0c0.apk is not the leanback version. This file is 85 MB in size, leanfront is 5 MB in size. You may have both installed. The icons look similar. Make sure you run the correct one. Also note that when you install mythbackend it will revert to the default theme. You can change themes.

**Comment by tunerooster** [comment]
Peter, you are right.  When I
installed mythfrontend-20190724-arm-v31-Pre-539-gff6bd41e0c0.apk Leanback
showed up in the next available slot in my favorites and I just assumed it
was what I had just installed.  Now that I have the right app, here's what
happened:
. Even after setting the database unique identifier, my setting were not
restored.
. With all default settings, audio did not work until I selected
"audiotrack".
. With only "audiotrack" set (all other options default), I am not able to
reproduce the problem, despite a *lot* of seeking around.

Because I had many settings I used often (mostly keystroke
bindings configured for the Shield remote), I tried the following:
. I removed the "database unique identifier" completely, and all my
settings re-appeared.
. But in that state, I was able to easily reproduce the problem.

So it seems clear that something in my settings is causing the problem.
Suspecting the Setup->Video->Playback->Current Video Playback
Profile customizations which were setup in the original install
instructions for the "Shield" release, I set it back to the default
"MediaCodec Normal", but that made no difference.

I am not sure where to go from here.  Do you have any suggestions for where
else to start eliminating the setting changes between the defaults and my
changes?

**Comment by bennettpeter** [comment]
I don't know any easy way to compare settings. If you find out what setting is causing the problem, please let us know so that we can investigate and fix it.

**Comment by tunerooster** [comment]
I have been trying to figure out how to isolate the setting which is
causing the problem, but in the mean time, while using the system with the
default settings, I have encountered the problem again, though it seems not
as often (but it is hard to tell since it is so intermittent to begin
with).  So I have concluded that I was mistaken when I said things work
with the default settings.

What that means is I am unable to get the Pre-539 release to work on the
tube (even though it works on the original shield).  I don't know what that
could mean, unless it is something to do with the different android
versions each is running.

I am at a loss...  Do you have any more ideas how to isolate this?

Thanks for your continued help!

**Comment by bennettpeter** [comment]
Closing because we are unable to reproduce the problem.
